name: Lambda Pipeline

on:
  push:
    branches: ["develop", "main"]

  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["develop"]

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: Deploy Lambda with Terraform
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_username: ${{ secrets.DATABASE_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DATABASE_PASSWORD }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve

  create-pr:
    name: Create PR to main
    needs: terraform
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head develop \
            --title "Criação de PR automatico para main" \
            --body "Um Pull request automatico foi criado para a branch main após o deploy bem-sucedido do Terraform." \
            || echo "PR ja existe e não sera criado."